name: Comment on PR
description: Comments on a pull request.

inputs:
  github_token:
    description: 'GitHub token for authentication'
    required: true
  pr_comment:
    description: 'Comment to post on the PR'
    required: true

runs:
  using: "composite"
  steps:
    - name: Write comment to file
      shell: bash
      run: |
        printf '%s\n' "${{ inputs.pr_comment }}" > pr_comment.txt
        cat pr_comment.txt

    - name: Escape special characters in pr_comment
      id: escape
      shell: bash
      run: |
        escaped_pr_comment=$(jq -Rsa . < pr_comment.txt)
        echo "::set-output name=escaped_pr_comment::$escaped_pr_comment"

    - name: Post comment to PR
      shell: bash
      run: |
        JSON_PAYLOAD=$(jq -n --arg body "${{ steps.escape.outputs.escaped_pr_comment }}" '{"body": $body}')
        
        echo "Generated JSON payload:"
        echo "$JSON_PAYLOAD"
        
        curl -X POST \
            -H "Authorization: Bearer ${{ inputs.github_token }}" \
            -H "Content-Type: application/json" \
            -d "$JSON_PAYLOAD" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
