name: Comment on PR
description: Comments on a pull request.

inputs:
  github_token:
    description: 'GitHub token for authentication'
    required: true
  pr_comment:
    description: 'Comment to post on the PR'
    required: true

runs:
  using: "composite"
  steps:
    - name: Run comment script
      shell: bash
      run: |
        echo "${{ inputs.pr_comment }}" >> pr_comment.txt
        cat pr_comment.txt
        # Escape special characters in pr_comment
        escaped_pr_comment=$(printf '%s\n' "${{ inputs.pr_comment }}" | jq -R .)

        # JSON_PAYLOAD=$(jq -n --arg body "$escaped_pr_comment" '{"body": $body}')
        JSON_PAYLOAD={\"body\":\"$(cat pr_comment.txt)\"}
        
        echo "Generated JSON payload:"
        echo "$JSON_PAYLOAD"
        
        curl -X POST \
            -H "Authorization: Bearer ${{ inputs.github_token }}" \
            -H "Content-Type: application/json" \
            -d "$JSON_PAYLOAD" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
