name: Fetch Latest Main
description: Fetches the latest changes from the main branch

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

      - name: Checkout main branch
        run: git checkout main

      - name: Pull latest changes
        run: git pull origin main
