name: Dev Release to GitHub
on:
  push:
    branches:
      - 'dev'
  workflow_dispatch:

jobs:
  call-release-workflow:
    name: Dev Release
    uses: ./.github/workflows/release.yaml
    with:
      branch: 'dev'