name: Main Release to GitHub

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to use for the workflow'
        required: true
        default: 'main'

jobs:
  merge-dev-to-main:
    name: Merge dev to main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ secrets.GITHUB_EMAIL }}"

      - name: Checkout dev branch
        run: git checkout dev

      - name: Merge dev into main
        run: |
          git checkout main
          git merge dev --no-ff
          git push origin main

  release:
    name: Release
    needs: merge-dev-to-main
    if: ${{ success() }}
    uses: ./.github/workflows/release.yml
    with:
      branch: 'main'

  merge-main-to-dev:
    name: Merge main back to dev
    needs: [merge-dev-to-main, release]
    if: ${{ success() }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ secrets.GITHUB_EMAIL }}"

      
      - name: Fetch changes in main
        uses: ./.github/actions/fetch-latest-main

      - name: Merge main into dev
        run: |
          git checkout dev
          git merge main --no-ff
          git push origin dev

  notify-on-failure:
    name: Notify on Failure
    needs: [merge-dev-to-main, release, merge-main-to-dev]
    if: ${{ failure() }}
    runs-on: ubuntu-latest

    steps:
      - name: Notify Failure
        run: |
          echo "Merge or Release process failed. Check the logs for details."
          # Add your preferred notification method here, e.g., send an email, create a GitHub issue, post a Slack message, etc.
