name: Merge Dev to Main

on:
  workflow_dispatch:

jobs:
  merge-dev-to-main:
    name: Merge dev to main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ secrets.GITHUB_EMAIL }}"

      - name: Checkout dev branch
        run: git checkout dev

      - name: Merge dev into main
        run: |
          git checkout main
          git merge dev --no-ff
          git push origin main

  notify-on-failure:
    name: Notify on Failure
    needs: [merge-dev-to-main]
    if: ${{ failure() }}
    runs-on: ubuntu-latest

    steps:
      - name: Notify Failure
        run: |
          echo "Merge or Release process failed. Check the logs for details."
          # Add notification for stakeholders here, e.g., send an email, create a GitHub issue, post a Slack message, etc.
